"""
CLIP prompt calibration: find prompt pairs that separate real vs AI video.

Run: python scripts/calibrate_clip_prompts.py

Tests many candidate prompt pairs against frames from all sample videos,
measuring which pair gives the best separation (AI scores high, real scores low).
"""
from __future__ import annotations

import sys
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

# ── Candidate prompt pairs ──
# Each entry: (name, real_prompts, fake_prompts)
CANDIDATE_PAIRS: list[tuple[str, list[str], list[str]]] = [
    (
        "current (photograph vs AI image)",
        [
            "a real photograph",
            "an authentic photo taken by a camera",
            "a genuine unedited photograph",
            "a real video frame captured by a camera",
            "natural photography",
        ],
        [
            "an AI generated image",
            "a synthetic image created by artificial intelligence",
            "a deepfake image",
            "a computer generated image",
            "an image generated by a diffusion model",
            "a fake image made by AI",
        ],
    ),
    (
        "video-specific",
        [
            "a frame from a real video",
            "a real video frame recorded by a camera",
            "authentic video footage",
        ],
        [
            "a frame from an AI-generated video",
            "a fake video frame created by AI",
            "synthetic video content",
        ],
    ),
    (
        "camera vs synthetic",
        [
            "authentic video footage from a camera",
            "genuine camera recording",
            "real footage captured on a physical camera",
        ],
        [
            "synthetic video created by AI",
            "artificially generated video content",
            "video produced by a neural network",
        ],
    ),
    (
        "natural vs computer",
        [
            "natural unedited video",
            "unprocessed natural footage",
            "raw video from a camera",
        ],
        [
            "computer generated video",
            "CGI rendered video",
            "computationally synthesized video",
        ],
    ),
    (
        "scene framing",
        [
            "a real scene captured on camera",
            "a natural scene from real life",
            "a genuine scene recorded by a person",
        ],
        [
            "an artificially created scene",
            "a scene generated by artificial intelligence",
            "a fake scene that does not exist in reality",
        ],
    ),
    (
        "unmodified vs synthesized",
        [
            "unmodified camera footage",
            "original unaltered video",
            "untouched camera recording",
        ],
        [
            "AI synthesized content",
            "machine-generated visual content",
            "content produced by a generative model",
        ],
    ),
    (
        "sensor vs neural net",
        [
            "camera sensor output",
            "optical sensor capture",
            "image from a physical camera sensor",
        ],
        [
            "neural network output",
            "image generated by a neural network",
            "output of a generative AI model",
        ],
    ),
    (
        "negation style",
        [
            "not AI generated",
            "not artificially created",
            "not computer generated",
        ],
        [
            "AI generated",
            "artificially created",
            "computer generated",
        ],
    ),
    (
        "minimal (real vs fake)",
        ["real", "authentic", "genuine"],
        ["fake", "synthetic", "artificial"],
    ),
    (
        "broadcast vs deepfake",
        [
            "broadcast video",
            "television footage",
            "professional camera recording",
        ],
        [
            "deepfake video",
            "manipulated video",
            "AI-altered video footage",
        ],
    ),
    (
        "photo realism focus",
        [
            "a photorealistic image from a camera",
            "a high fidelity photograph",
            "an image with natural camera noise and lens artifacts",
        ],
        [
            "a photorealistic image generated by AI",
            "a convincing fake image from a diffusion model",
            "an AI image mimicking photography",
        ],
    ),
    (
        "texture + artifact",
        [
            "an image with natural film grain and sensor noise",
            "a photo with real optical imperfections",
            "natural image with camera artifacts",
        ],
        [
            "an image with unnaturally smooth textures",
            "a synthetic image lacking sensor noise",
            "an AI image with artificial smoothness",
        ],
    ),
    (
        "content-agnostic",
        [
            "a real image",
            "a photograph",
            "an image captured in the real world",
        ],
        [
            "a generated image",
            "a synthetic image",
            "an image that was not captured by a camera",
        ],
    ),
    (
        "video temporal cues",
        [
            "a frame from footage recorded by a video camera",
            "a video frame with natural motion blur",
            "real-world video frame with optical artifacts",
        ],
        [
            "a frame from a video generated by AI",
            "a video frame rendered by a generative model",
            "synthetic video frame with no real-world origin",
        ],
    ),
]


def extract_frames(video_path: str, n: int = 10) -> list[np.ndarray]:
    """Extract n uniformly spaced frames from a video."""
    cap = cv2.VideoCapture(video_path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total == 0:
        cap.release()
        return []
    indices = np.linspace(0, total - 1, n, dtype=int)
    frames = []
    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(idx))
        ret, frame = cap.read()
        if ret:
            frames.append(frame)
    cap.release()
    return frames


def get_video_label(video_path: Path) -> str:
    """Heuristic label: 'real' or 'ai' based on filename conventions."""
    name = video_path.stem.lower()
    real_indicators = ["real", "authentic", "genuine", "sample"]
    ai_indicators = [
        "capybara", "sora", "veo", "runway", "midjourney",
        "generated", "synthetic", "fake", "deepfake",
    ]
    for ind in ai_indicators:
        if ind in name:
            return "ai"
    for ind in real_indicators:
        if ind in name:
            return "real"
    # Default: unknown — skip from separation calc
    return "unknown"


def main():
    import open_clip
    import torch
    from torchvision import transforms

    device = "mps" if torch.backends.mps.is_available() else "cpu"

    # ── Load CLIP model ──
    print("Loading CLIP ViT-L/14...")
    model, _, _ = open_clip.create_model_and_transforms(
        "ViT-L-14", pretrained="openai",
    )
    model = model.to(device)
    model.eval()
    tokenizer = open_clip.get_tokenizer("ViT-L-14")

    transform = transforms.Compose([
        transforms.ToPILImage(),
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.48145466, 0.4578275, 0.40821073],
            std=[0.26862954, 0.26130258, 0.27577711],
        ),
    ])
    print("CLIP loaded.\n")

    # ── Find and classify videos ──
    sample_dir = Path("data/sample_videos")
    videos = sorted(sample_dir.glob("*.mp4")) + sorted(
        sample_dir.glob("*.mov"),
    )
    if not videos:
        print("No videos found in data/sample_videos/")
        return

    video_info = []
    for vpath in videos:
        label = get_video_label(vpath)
        frames = extract_frames(str(vpath), n=10)
        if not frames:
            continue
        video_info.append({"path": vpath, "label": label, "frames": frames})
        print(f"  {vpath.name}: {len(frames)} frames, label={label}")

    real_videos = [v for v in video_info if v["label"] == "real"]
    ai_videos = [v for v in video_info if v["label"] == "ai"]

    if not real_videos or not ai_videos:
        print(
            "\nNeed at least one 'real' and one 'ai'"
            " video for separation analysis.",
        )
        print(
            "Label is inferred from filename."
            " Rename videos or edit get_video_label().",
        )
        # Still run and show all scores
        if not real_videos and not ai_videos:
            return

    # ── Pre-encode all frames ──
    print("\nEncoding frames...")
    all_frames_by_video = {}
    for v in video_info:
        tensors = [transform(f[:, :, ::-1].copy()) for f in v["frames"]]
        batch = torch.stack(tensors).to(device)
        with torch.no_grad():
            feats = model.encode_image(batch)
            feats = feats / feats.norm(dim=-1, keepdim=True)
        all_frames_by_video[str(v["path"])] = feats
    print("Frames encoded.\n")

    # ── Evaluate each prompt pair ──
    results = []

    for pair_name, real_prompts, fake_prompts in CANDIDATE_PAIRS:
        # Encode prompts
        with torch.no_grad():
            real_tokens = tokenizer(real_prompts).to(device)
            real_text = model.encode_text(real_tokens)
            real_text = real_text / real_text.norm(dim=-1, keepdim=True)
            real_text_avg = real_text.mean(dim=0, keepdim=True)
            real_text_avg = real_text_avg / real_text_avg.norm(dim=-1, keepdim=True)

            fake_tokens = tokenizer(fake_prompts).to(device)
            fake_text = model.encode_text(fake_tokens)
            fake_text = fake_text / fake_text.norm(dim=-1, keepdim=True)
            fake_text_avg = fake_text.mean(dim=0, keepdim=True)
            fake_text_avg = fake_text_avg / fake_text_avg.norm(dim=-1, keepdim=True)

        # Score every video
        per_video_scores = {}
        for v in video_info:
            feats = all_frames_by_video[str(v["path"])]
            with torch.no_grad():
                sim_real = (feats @ real_text_avg.T).squeeze(-1)
                sim_fake = (feats @ fake_text_avg.T).squeeze(-1)
                logits = torch.stack([sim_fake, sim_real], dim=-1) * 100.0
                probs = torch.softmax(logits, dim=-1)
                fake_scores = probs[:, 0].cpu().numpy()

            per_video_scores[str(v["path"])] = {
                "label": v["label"],
                "name": v["path"].name,
                "scores": fake_scores.tolist(),
                "mean": float(fake_scores.mean()),
                "std": float(fake_scores.std()),
            }

        # Aggregate by label
        real_means = [s["mean"] for s in per_video_scores.values() if s["label"] == "real"]
        ai_means = [s["mean"] for s in per_video_scores.values() if s["label"] == "ai"]

        real_overall = float(np.mean(real_means)) if real_means else None
        ai_overall = float(np.mean(ai_means)) if ai_means else None

        if real_overall is not None and ai_overall is not None:
            gap = ai_overall - real_overall
        else:
            gap = None

        results.append({
            "name": pair_name,
            "real_prompts": real_prompts,
            "fake_prompts": fake_prompts,
            "per_video": per_video_scores,
            "real_mean": real_overall,
            "ai_mean": ai_overall,
            "gap": gap,
        })

    # ── Print detailed per-pair results ──
    print("=" * 90)
    print("  DETAILED RESULTS — Per-video scores for each prompt pair")
    print("=" * 90)

    for r in results:
        print(f"\n  Prompt pair: {r['name']}")
        print(f"  Real prompts: {r['real_prompts'][:2]}...")
        print(f"  Fake prompts: {r['fake_prompts'][:2]}...")
        print(f"  {'Video':<40} {'Label':>6} {'Mean':>7} {'Std':>7} {'Min':>7} {'Max':>7}")
        print(f"  {'─' * 40} {'─' * 6} {'─' * 7} {'─' * 7} {'─' * 7} {'─' * 7}")

        for v_path, v_data in r["per_video"].items():
            scores = v_data["scores"]
            print(
                f"  {v_data['name']:<40} {v_data['label']:>6} "
                f"{v_data['mean']:>7.3f} {v_data['std']:>7.3f} "
                f"{min(scores):>7.3f} {max(scores):>7.3f}"
            )

    # ── Summary ranking table ──
    print(f"\n\n{'=' * 90}")
    print("  RANKING — Prompt pairs sorted by separation gap (AI_mean - Real_mean)")
    print(f"{'=' * 90}")
    print("  Higher gap = better separation. Positive = correct direction (AI > Real).")
    print("  Negative = ANTI-CORRELATED (real scores higher than AI).\n")

    ranked = sorted(results, key=lambda r: r["gap"] if r["gap"] is not None else -999, reverse=True)

    header = (
        f"  {'#':>3}  {'Prompt pair':<35} {'Real mean':>10}"
        f" {'AI mean':>10} {'Gap':>10} {'Direction':>12}"
    )
    print(header)
    print(f"  {'─' * 3}  {'─' * 35} {'─' * 10} {'─' * 10} {'─' * 10} {'─' * 12}")

    for i, r in enumerate(ranked, 1):
        if r["gap"] is not None:
            direction = "CORRECT" if r["gap"] > 0 else "INVERTED"
            marker = "  <<<" if r["gap"] > 0.05 else (" !!!" if r["gap"] < -0.05 else "")
            print(
                f"  {i:>3}  {r['name']:<35} {r['real_mean']:>10.4f} "
                f"{r['ai_mean']:>10.4f} {r['gap']:>+10.4f} {direction:>12}{marker}"
            )
        else:
            print(f"  {i:>3}  {r['name']:<35} {'N/A':>10} {'N/A':>10} {'N/A':>10} {'N/A':>12}")

    # ── Best pair recommendation ──
    valid = [r for r in ranked if r["gap"] is not None]
    if valid:
        best = valid[0]
        worst = valid[-1]
        print(f"\n  BEST:  {best['name']} (gap={best['gap']:+.4f})")
        print(f"    Real prompts: {best['real_prompts']}")
        print(f"    Fake prompts: {best['fake_prompts']}")
        if best["gap"] <= 0:
            print("\n  WARNING: Even the best pair is anti-correlated or zero-gap.")
            print("  Zero-shot CLIP may not separate these specific videos.")
            print("  Consider fine-tuned weights for this content type.")
        print(f"\n  WORST: {worst['name']} (gap={worst['gap']:+.4f})")

    print()


if __name__ == "__main__":
    main()
