"""
CLIP ViT-L/14 deepfake detector — FIXED with zero-shot classification.

Save to: src/verifi/detectors/clip_detector.py (REPLACES existing file)

Key change: Instead of a random nn.Linear classifier head, this uses
CLIP's native zero-shot capability — comparing image embeddings against
text prompts for "real photograph" vs "AI generated image".

This works out-of-the-box with any CLIP model, no fine-tuning needed.
"""
import numpy as np
import open_clip
import structlog
import torch
from torchvision import transforms

from verifi.detectors.base import BaseDetector, DetectionResult

logger = structlog.get_logger()

# Zero-shot prompt pairs — CLIP compares image against these
# Multiple prompts per class improves robustness (prompt ensembling)
REAL_PROMPTS = [
    "a real photograph",
    "an authentic photo taken by a camera",
    "a genuine unedited photograph",
    "a real video frame captured by a camera",
    "natural photography",
]

FAKE_PROMPTS = [
    "an AI generated image",
    "a synthetic image created by artificial intelligence",
    "a deepfake image",
    "a computer generated image",
    "an image generated by a diffusion model",
    "a fake image made by AI",
]


class CLIPDeepfakeDetector(BaseDetector):
    """
    CLIP ViT-L/14 deepfake detector using zero-shot classification.

    Instead of a fine-tuned classifier head (which needs trained weights),
    this uses CLIP's text-image similarity to compare each frame against
    "real" and "fake" text descriptions. This works immediately with
    any pre-trained CLIP model.

    For face-swap detection, fine-tuned weights (LN-tuned on FF++) give
    better results. For fully synthetic content detection, zero-shot
    is surprisingly competitive because CLIP learned to distinguish
    photographic vs synthetic images during pre-training.
    """

    def __init__(self, weight_path: str, device: str, input_size: int = 224):
        super().__init__(device)
        self.weight_path = weight_path
        self.input_size = input_size
        self._tokenizer = None
        self._real_features = None
        self._fake_features = None
        self._model_format = "zero_shot"

        self._transform = transforms.Compose([
            transforms.ToPILImage(),
            transforms.Resize((input_size, input_size)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.48145466, 0.4578275, 0.40821073],
                std=[0.26862954, 0.26130258, 0.27577711],
            ),
        ])

    def load(self) -> None:
        logger.info("loading_clip_detector", device=self.device, mode="zero_shot")

        # Load CLIP model + tokenizer
        self._model, _, _ = open_clip.create_model_and_transforms(
            "ViT-L-14", pretrained="openai"
        )
        self._model = self._model.to(self.device)
        self._model.eval()
        self._tokenizer = open_clip.get_tokenizer("ViT-L-14")

        # Pre-compute text embeddings for real/fake prompts
        self._real_features = self._encode_prompts(REAL_PROMPTS)
        self._fake_features = self._encode_prompts(FAKE_PROMPTS)

        self._loaded = True
        logger.info("clip_loaded", format="zero_shot", num_real_prompts=len(REAL_PROMPTS),
                     num_fake_prompts=len(FAKE_PROMPTS))

    def _encode_prompts(self, prompts: list[str]) -> torch.Tensor:
        """Encode text prompts into averaged CLIP text embeddings."""
        tokens = self._tokenizer(prompts).to(self.device)
        with torch.no_grad():
            text_features = self._model.encode_text(tokens)
            text_features = text_features / text_features.norm(dim=-1, keepdim=True)
            # Average across all prompts for this class
            avg_features = text_features.mean(dim=0, keepdim=True)
            avg_features = avg_features / avg_features.norm(dim=-1, keepdim=True)
        return avg_features

    def predict(self, face_crops: list[np.ndarray]) -> list[DetectionResult]:
        if not face_crops or not self._loaded:
            return []

        # Batch transform: BGR → RGB → normalized tensor
        tensors = []
        for crop in face_crops:
            rgb = crop[:, :, ::-1].copy()
            tensors.append(self._transform(rgb))

        batch = torch.stack(tensors).to(self.device)

        with torch.no_grad():
            # Encode images
            image_features = self._model.encode_image(batch)
            image_features = image_features / image_features.norm(dim=-1, keepdim=True)

            # Compute similarity to real and fake prompts
            sim_real = (image_features @ self._real_features.T).squeeze(-1)
            sim_fake = (image_features @ self._fake_features.T).squeeze(-1)

            # Stack and softmax to get probabilities
            logits = torch.stack([sim_fake, sim_real], dim=-1) * 100.0  # CLIP logit scale
            probs = torch.softmax(logits, dim=-1)
            fake_probs = probs[:, 0].cpu().numpy()  # P(fake)

        return [
            DetectionResult(
                score=float(p),
                raw_logits=logits[i].cpu().numpy(),
                metadata={
                    "sim_real": float(sim_real[i].cpu()),
                    "sim_fake": float(sim_fake[i].cpu()),
                },
            )
            for i, p in enumerate(fake_probs)
        ]

    def get_gradcam_target_layer(self):
        """
        Target the last transformer block's LayerNorm for GradCAM.
        This is where the visual features are most semantically rich.
        """
        try:
            return self._model.visual.transformer.resblocks[-1].ln_2
        except AttributeError:
            logger.warn("gradcam_layer_not_found")
            return None

    def get_visual_model(self) -> torch.nn.Module:
        """Return the visual encoder for GradCAM (separate from text encoder)."""
        return self._model.visual
