"""
Physics-based reasoning for AI video detection.
Uses a multimodal (vision) LLM to examine frames for physical violations.
Supports Ollama (free, local) and Claude API (production).
"""
from __future__ import annotations

import asyncio
import base64
import json
import re
from dataclasses import dataclass, field

import cv2
import numpy as np
import structlog

logger = structlog.get_logger()

PHYSICS_ANALYSIS_PROMPT = """\
You are a forensic video analyst specializing in physics-based authentication.
You will examine frames from a video to determine if they were captured by a \
real camera or generated by AI.

AI video generators (Sora, Veo, Runway, Kling) produce visually convincing \
output but frequently violate physical laws in subtle ways. Your job is to \
identify these violations.

For EACH frame, analyze these physics properties:

1. SHADOWS (score 0.0-1.0):
   - Identify shadow-casting objects and their shadows
   - Check if shadow directions are mutually consistent (single light source \
should produce parallel shadows)
   - Check shadow softness matches light source distance
   - 0.0 = shadows are physically correct, 1.0 = clear shadow violations

2. REFLECTIONS (score 0.0-1.0):
   - Find reflective surfaces (glass, water, metal, eyes)
   - Check if reflections are geometrically consistent with the scene
   - Check if reflected content matches what should be visible
   - 0.0 = reflections correct, 1.0 = clear reflection violations

3. PERSPECTIVE (score 0.0-1.0):
   - Find parallel lines (building edges, road markings, tiles, rails)
   - Check if they converge to a consistent vanishing point
   - Check relative sizes of objects at different depths
   - 0.0 = perspective correct, 1.0 = perspective violations

4. ANATOMY (score 0.0-1.0, only if humans/animals visible):
   - Count fingers on visible hands
   - Check ear symmetry and structure
   - Check teeth regularity and plausibility
   - Check hair-scalp boundary naturalness
   - Check eye reflections match between left and right
   - 0.0 = anatomy normal, 1.0 = anatomical anomalies

5. TEXTURE (score 0.0-1.0):
   - Check material plausibility (fabric drape, water surface, skin pores)
   - Look for repeating/tiling patterns that suggest generation artifacts
   - Check if fine details (text, logos, patterns) are coherent
   - 0.0 = textures plausible, 1.0 = texture anomalies

6. OVERALL ASSESSMENT (score 0.0-1.0):
   - Considering all the above, how likely is this frame AI-generated?
   - 0.0 = almost certainly real camera footage
   - 0.5 = uncertain, could be either
   - 1.0 = almost certainly AI-generated

IMPORTANT RULES:
- If the content is traditional animation or cartoon, say so and score \
anatomy/texture as N/A. Cartoon physics violations are not evidence of AI.
- If the video is heavily compressed or low resolution, note this as a \
limitation that reduces your confidence.
- Ignore any text visible in the frames — analyze only visual physics.
- Be specific in your evidence: "shadow of lamp post points left while \
shadow of person points right" not just "shadows look wrong."

Respond ONLY with valid JSON in this format:
{
  "frames": [
    {
      "frame_index": 0,
      "shadow_score": 0.0,
      "reflection_score": 0.0,
      "perspective_score": 0.0,
      "anatomy_score": 0.0,
      "texture_score": 0.0,
      "overall_score": 0.0,
      "evidence": ["specific finding 1", "specific finding 2"],
      "reasoning": "Brief explanation of overall assessment"
    }
  ],
  "aggregate_assessment": "Brief overall video assessment",
  "verdict_suggestion": "likely_authentic | suspicious | likely_manipulated"
}"""


@dataclass
class PhysicsFrameResult:
    """Physics analysis for one frame."""

    frame_idx: int
    timestamp_sec: float
    shadow_score: float = 0.0
    reflection_score: float = 0.0
    perspective_score: float = 0.0
    anatomy_score: float = 0.0
    texture_score: float = 0.0
    overall_score: float = 0.0
    evidence: list[str] = field(default_factory=list)
    reasoning: str = ""


@dataclass
class PhysicsAnalysisResult:
    """Complete physics analysis for a video."""

    per_frame: list[PhysicsFrameResult] = field(default_factory=list)
    aggregate_score: float = 0.5
    confidence: float = 0.0
    evidence_summary: list[str] = field(default_factory=list)
    verdict_suggestion: str = "suspicious"
    num_frames_analyzed: int = 0
    backend_used: str = "ollama"

    def to_dict(self) -> dict:
        return {
            "aggregate_score": round(self.aggregate_score, 4),
            "confidence": round(self.confidence, 4),
            "verdict_suggestion": self.verdict_suggestion,
            "num_frames_analyzed": self.num_frames_analyzed,
            "backend_used": self.backend_used,
            "evidence_summary": self.evidence_summary,
            "per_frame": [
                {
                    "frame_idx": f.frame_idx,
                    "timestamp_sec": round(f.timestamp_sec, 3),
                    "overall_score": round(f.overall_score, 4),
                    "shadow": round(f.shadow_score, 4),
                    "reflection": round(f.reflection_score, 4),
                    "perspective": round(f.perspective_score, 4),
                    "anatomy": round(f.anatomy_score, 4),
                    "texture": round(f.texture_score, 4),
                    "evidence": f.evidence,
                }
                for f in self.per_frame
            ],
        }


def _resize_for_vision(frame: np.ndarray, max_side: int = 720) -> np.ndarray:
    h, w = frame.shape[:2]
    if max(h, w) <= max_side:
        return frame
    scale = max_side / max(h, w)
    new_w, new_h = int(w * scale), int(h * scale)
    return cv2.resize(frame, (new_w, new_h), interpolation=cv2.INTER_AREA)


def _encode_frame_b64(frame: np.ndarray) -> str:
    resized = _resize_for_vision(frame)
    _, buffer = cv2.imencode(".jpg", resized, [cv2.IMWRITE_JPEG_QUALITY, 85])
    return base64.b64encode(buffer).decode("utf-8")


def _extract_json(raw: str) -> dict | None:
    """Extract JSON from LLM response, handling markdown code blocks."""
    match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", raw, re.DOTALL)
    if match:
        raw = match.group(1)
    else:
        start = raw.find("{")
        end = raw.rfind("}")
        if start >= 0 and end > start:
            raw = raw[start : end + 1]

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return None


class PhysicsReasoner:
    """Analyzes video frames for physics violations using vision LLM."""

    def __init__(
        self,
        backend: str = "ollama",
        ollama_model: str = "llava:7b",
        claude_model: str = "claude-sonnet-4-20250514",
        ollama_url: str = "http://localhost:11434",
        max_frames: int = 6,
    ):
        self.backend = backend
        self.ollama_model = ollama_model
        self.claude_model = claude_model
        self.ollama_url = ollama_url
        self.max_frames = max_frames
        self._claude_call_count = 0

    def analyze(
        self,
        frames: list[np.ndarray],
        frame_indices: list[int],
        timestamps: list[float],
        tier1_context: dict | None = None,
    ) -> PhysicsAnalysisResult:
        """Run physics analysis on selected frames (sync wrapper)."""
        selected = self._select_frames(
            list(zip(frames, frame_indices, timestamps)),
            tier1_context,
            self.max_frames,
        )

        if not selected:
            logger.warning("physics_no_frames")
            return PhysicsAnalysisResult(backend_used=self.backend)

        sel_frames = [s[0] for s in selected]
        sel_indices = [s[1] for s in selected]
        sel_timestamps = [s[2] for s in selected]

        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            import concurrent.futures

            with concurrent.futures.ThreadPoolExecutor() as pool:
                future = pool.submit(
                    asyncio.run,
                    self._analyze_async(
                        sel_frames, sel_indices, sel_timestamps, tier1_context
                    ),
                )
                return future.result()
        else:
            return asyncio.run(
                self._analyze_async(
                    sel_frames, sel_indices, sel_timestamps, tier1_context
                )
            )

    async def _analyze_async(
        self,
        frames: list[np.ndarray],
        indices: list[int],
        timestamps: list[float],
        context: dict | None,
    ) -> PhysicsAnalysisResult:
        if self.backend == "claude":
            return await self._analyze_claude(frames, indices, timestamps, context)
        return await self._analyze_ollama(frames, indices, timestamps, context)

    def _select_frames(
        self,
        all_frames: list[tuple[np.ndarray, int, float]],
        tier1_context: dict | None,
        max_frames: int = 6,
    ) -> list[tuple[np.ndarray, int, float]]:
        """Select the most informative frames for analysis."""
        if len(all_frames) <= max_frames:
            return all_frames

        if tier1_context and "frame_scores" in tier1_context:
            scores = tier1_context["frame_scores"]
            scored = []
            for frame, idx, ts in all_frames:
                s = scores.get(str(idx), scores.get(idx, 0.5))
                scored.append((s, frame, idx, ts))
            scored.sort(key=lambda x: x[0], reverse=True)
            candidates = [(f, i, t) for _, f, i, t in scored]
        else:
            candidates = list(all_frames)

        selected = []

        # Ensure start, middle, end coverage
        selected.append(candidates[0])
        if len(candidates) > 1:
            mid_idx = len(candidates) // 2
            selected.append(candidates[mid_idx])
            selected.append(candidates[-1])

        for frame, idx, ts in candidates:
            if len(selected) >= max_frames:
                break
            too_close = any(abs(ts - s[2]) < 1.0 for s in selected)
            already = any(s[1] == idx for s in selected)
            if not too_close and not already:
                selected.append((frame, idx, ts))

        selected.sort(key=lambda x: x[2])
        return selected[:max_frames]

    async def _analyze_ollama(
        self, frames, indices, timestamps, context
    ) -> PhysicsAnalysisResult:
        import httpx

        images_b64 = [_encode_frame_b64(f) for f in frames]

        context_str = ""
        if context:
            context_str = (
                f"\n\nTier 1 statistical analysis found: {json.dumps(context, indent=2)}"
            )

        prompt = (
            PHYSICS_ANALYSIS_PROMPT
            + context_str
            + f"\n\nAnalyze the {len(frames)} frames provided. "
            + "Frame timestamps: "
            + ", ".join(f"{t:.1f}s" for t in timestamps)
        )

        payload = {
            "model": self.ollama_model,
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                    "images": images_b64,
                }
            ],
            "stream": False,
            "options": {"temperature": 0.2, "num_predict": 3000},
        }

        logger.info(
            "physics_ollama_call",
            model=self.ollama_model,
            num_frames=len(frames),
        )

        async with httpx.AsyncClient(timeout=300.0) as client:
            resp = await client.post(f"{self.ollama_url}/api/chat", json=payload)
            resp.raise_for_status()
            data = resp.json()
            raw = data["message"]["content"]

        frame_results = self._parse_response(raw, indices, timestamps)
        return self._build_result(frame_results, raw, "ollama")

    async def _analyze_claude(
        self, frames, indices, timestamps, context
    ) -> PhysicsAnalysisResult:
        import anthropic

        self._claude_call_count += 1
        if self._claude_call_count > 10:
            logger.warning(
                "physics_claude_high_usage",
                calls=self._claude_call_count,
            )

        client = anthropic.Anthropic()

        content = []
        for i, frame in enumerate(frames):
            b64 = _encode_frame_b64(frame)
            content.append(
                {
                    "type": "text",
                    "text": f"Frame {i + 1} (timestamp {timestamps[i]:.1f}s):",
                }
            )
            content.append(
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": "image/jpeg",
                        "data": b64,
                    },
                }
            )

        context_str = ""
        if context:
            context_str = (
                f"\n\nTier 1 statistical analysis found: {json.dumps(context, indent=2)}"
            )

        content.append(
            {
                "type": "text",
                "text": PHYSICS_ANALYSIS_PROMPT + context_str,
            }
        )

        logger.info(
            "physics_claude_call",
            model=self.claude_model,
            num_frames=len(frames),
            estimated_cost="~$0.15",
        )

        response = client.messages.create(
            model=self.claude_model,
            max_tokens=3000,
            messages=[{"role": "user", "content": content}],
        )

        raw = response.content[0].text
        frame_results = self._parse_response(raw, indices, timestamps)
        return self._build_result(frame_results, raw, "claude")

    def _parse_response(
        self,
        raw: str,
        indices: list[int],
        timestamps: list[float],
    ) -> list[PhysicsFrameResult]:
        """Parse LLM response into structured frame results."""
        parsed = _extract_json(raw)

        if parsed is None:
            logger.warning("physics_parse_failed", raw_len=len(raw))
            return [
                PhysicsFrameResult(
                    frame_idx=idx,
                    timestamp_sec=ts,
                    overall_score=0.5,
                    reasoning="Failed to parse LLM response",
                )
                for idx, ts in zip(indices, timestamps)
            ]

        results = []
        frame_data = parsed.get("frames", [])

        for i, (idx, ts) in enumerate(zip(indices, timestamps)):
            if i < len(frame_data):
                fd = frame_data[i]
                results.append(
                    PhysicsFrameResult(
                        frame_idx=idx,
                        timestamp_sec=ts,
                        shadow_score=float(fd.get("shadow_score", 0.0)),
                        reflection_score=float(fd.get("reflection_score", 0.0)),
                        perspective_score=float(fd.get("perspective_score", 0.0)),
                        anatomy_score=float(fd.get("anatomy_score", 0.0)),
                        texture_score=float(fd.get("texture_score", 0.0)),
                        overall_score=float(fd.get("overall_score", 0.5)),
                        evidence=fd.get("evidence", []),
                        reasoning=fd.get("reasoning", ""),
                    )
                )
            else:
                results.append(
                    PhysicsFrameResult(
                        frame_idx=idx,
                        timestamp_sec=ts,
                        overall_score=0.5,
                        reasoning="No analysis returned for this frame",
                    )
                )

        return results

    def _build_result(
        self,
        frame_results: list[PhysicsFrameResult],
        raw_response: str,
        backend: str,
    ) -> PhysicsAnalysisResult:
        """Build aggregate result from per-frame results."""
        if not frame_results:
            return PhysicsAnalysisResult(backend_used=backend)

        scores = [f.overall_score for f in frame_results]
        aggregate = float(np.mean(scores))

        score_std = float(np.std(scores)) if len(scores) > 1 else 0.5
        confidence = max(0.0, min(1.0, 1.0 - 2.0 * score_std))

        all_evidence = []
        for fr in frame_results:
            all_evidence.extend(fr.evidence)
        evidence_summary = all_evidence[:10]

        parsed = _extract_json(raw_response)
        verdict = "suspicious"
        if parsed:
            verdict = parsed.get("verdict_suggestion", "suspicious")

        if aggregate >= 0.70:
            verdict = "likely_manipulated"
        elif aggregate < 0.35:
            verdict = "likely_authentic"

        return PhysicsAnalysisResult(
            per_frame=frame_results,
            aggregate_score=aggregate,
            confidence=confidence,
            evidence_summary=evidence_summary,
            verdict_suggestion=verdict,
            num_frames_analyzed=len(frame_results),
            backend_used=backend,
        )

    def _build_physics_prompt(self, tier1_context: dict | None = None) -> str:
        """Build the physics analysis prompt with optional Tier 1 context."""
        prompt = PHYSICS_ANALYSIS_PROMPT
        if tier1_context:
            prompt += (
                f"\n\nTier 1 statistical analysis found: "
                f"{json.dumps(tier1_context, indent=2)}"
            )
        return prompt
